"""empty message

Revision ID: 00c1e401cf72
Revises: e16ab35ef51d
Create Date: 2026-08-17 12:53:27.890114

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "00c1e401cf72"
down_revision = "e16ab35ef51d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "product",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Integer(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("product")
    # ### end Alembic commands ###
