"""empty message

Revision ID: 08e0d44e4660
Revises: f7a5bdd48f4e
Create Date: 2026-09-19 00:26:19.293162

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "08e0d44e4660"
down_revision = "f7a5bdd48f4e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_chat_user_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(None, "main_user", ["user_id"], ["id"])

    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "main_user", ["sender_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("messages", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(None, "user", ["sender_id"], ["id"])

    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.create_foreign_key(
            batch_op.f("fk_chat_user_id"), "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###
