"""empty message

Revision ID: 44c310dc27d9
Revises: 45943ee7f837
Create Date: 2026-09-16 11:17:17.177451

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "44c310dc27d9"
down_revision = "45943ee7f837"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        batch_op.add_column(sa.Column("user_id", sa.Integer(), nullable=True))

        # Заменяем None на явно заданные имена
        batch_op.create_unique_constraint("uq_chat_user_id", ["user_id"])
        batch_op.create_foreign_key(
            "fk_chat_user_id", "user", ["user_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chat", schema=None) as batch_op:
        # Указываем те же самые имена для удаления
        batch_op.drop_constraint("fk_chat_user_id", type_="foreignkey")
        batch_op.drop_constraint("uq_chat_user_id", type_="unique")
        batch_op.drop_column("user_id")
    # ### end Alembic commands ###
