"""empty message

Revision ID: 45943ee7f837
Revises: a365446f89f2
Create Date: 2026-09-15 23:57:01.875082

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45943ee7f837'
down_revision = 'a365446f89f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('avatar', sa.String(), nullable=True),
    sa.Column('own', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat')
    # ### end Alembic commands ###
