"""empty message

Revision ID: 73480ece7a6d
Revises: 44c310dc27d9
Create Date: 2026-09-17 18:31:58.337542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73480ece7a6d'
down_revision = '44c310dc27d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('sender_id', sa.Integer(), nullable=True),
    sa.Column('chat_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['chat_id'], ['chat.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.drop_column('own')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('own', sa.BOOLEAN(), nullable=True))

    op.drop_table('messages')
    # ### end Alembic commands ###
